### ISSUE TITLE
[TF 50]  Block Edit While Form is Published

### ISSUE THREAD

**Issue by rithikasapparapu** [phanijyothi11-tamu/team-formation#126]
Feature : Block Edit While Form is Published
As a professor ,
So that I can avoid discrepancies in form responses ,
I want to be constrained from editing a form when it is open to students .

  Background:
    Given I log in as a professor

  Scenario: Professor cannot view responses for an unpublished form
    Given I have created a form that is not published
    When I visit my user profile page
    Then I should not see "View Responses" for that form
    And I should see "Edit" and "Delete" buttons for that form

  Scenario: Professor can view responses for a published form
    Given I have created a form that is published
    When I visit my user profile page
    Then I should see "View Responses" for that form
    And I should not see "Edit" or "Delete" buttons for that form

Background:
    Given I log in as a professor

  Scenario: View an unpublished form
    Given I have created a form that is not published
    When I navigate to my user profile page
    And I click on "View" for "Test Form"
    Then I should see the form details
    And I should see "Edit this form" button
    And I should see "Publish Form" button
    And I should see "Destroy this form" button
    And I should see "This form is not published yet"

  Scenario: View a published form
    Given I have created a form that is published
    When I navigate to my user profile page
    And I click on "View" for "Test Form"
    Then I should see the form details
    And I should see "Close Form" button
    And I should not see "Edit this form" button
    And I should not see "Destroy this form" button
    And I should see "This form has been published. To make any changes, please close the form first"

**Comment by urt23** [comment]
https://github.com/user-attachments/assets/9e774562-e0f1-42e1-af1b-bf6845634b39
