### ISSUE TITLE
[TF4] Professor adds a specific attribute

### ISSUE THREAD

**Issue by phanijyothi11-tamu** [phanijyothi11-tamu/team-formation#14]
Feature: Add Specific Attributes
  As a professor
  So that I can collect relevant information for team formation
  I want to add specific attributes to the form

  Background:
    Given I am logged in as a professor
    And I have created a form

  Scenario: Professor adds a specific attribute
    When I visit the edit page for the form
    Then I should see an option to add a new attribute
    When I enter "Programming Proficiency" as the attribute name
    And I select "Scale" as the attribute type
    And I enter "1" as the minimum value
    And I enter "8" as the maximum value
    And I submit the new attribute
    Then I should see "Programming Proficiency" listed as an attribute on the form
    
  Scenario: Attribute is saved to the database after submission
    When I visit the edit page for the form
    And I enter "Team Leadership" as the attribute name
    And I select "Scale" as the attribute type
    And I enter "1" as the minimum value
    And I enter "10" as the maximum value
    And I submit the new attribute
    Then the attribute "Team Leadership" should be saved in the database
    And the attribute "Team Leadership" should have a scale from 1 to 10

**Comment by urt23** [comment]
pull request : https://github.com/phanijyothi11-tamu/team-formation/pull/34

**Comment by phanijyothi11-tamu** [comment]
Implementations covered under this ticket:
Scenario : Professor adds a specific attribute
Given I am editing a form
When I select " Add Attribute "
And I enter " Programming Proficiency " as the attribute name
And I select " Scale 1 -8 " as the attribute type
Then " Programming Proficiency " should be added as an attribute to the form

**Comment by phanijyothi11-tamu** [comment]
Edit functionality implemented as a part of CREATE workflow:

Feature : Add New Attributes / Questions
As a professor ,
So that I can collect additional information if needed ,
I want to add new attributes or questions to an existing form .

Scenario : Professor adds a new question to an existing form
Given I am editing an existing form
When I click " Add Question "
And I enter the new question details
Then the new question should be added to the form

**Comment by phanijyothi11-tamu** [comment]
This ticket has been reviewed and marked as complete (closed).
