### ISSUE TITLE
Deployment for Sprint 4

### ISSUE THREAD

**Issue by urt23** [phanijyothi11-tamu/team-formation#205]
This ticket involves the deployment of features implemented during Sprint 4. The deployment process has been conducted in two phases, ensuring a seamless transition and minimizing potential disruptions in the production environment.  

1. **Batch Deployment:** Features were deployed in batches to ensure stability and allow for incremental testing.  
2. **Production Stability:** Thorough monitoring was conducted during and after each deployment phase to ensure the production environment remained stable and functional.  
3. **Final Verification:** All features and improvements from Sprint 4 were verified post-deployment to confirm successful integration and functionality.  

This deployment ensures that the Sprint 4 deliverables are live and fully operational.

**Comment by raju2102** [comment]
- latest release deployed in Heroku, will all the features tested end to end
