### ISSUE TITLE
[TF25] Feature : Publish form

### ISSUE THREAD

**Issue by muresaijaideepreddy** [phanijyothi11-tamu/team-formation#62]
Feature : Publish form
As a professor ,
I want to publish the form to the students ,
So that I can collect the data required to form teams .
Scenario : Successfully publishing a form
Given the form is ready with all required fields
When the professor clicks on " Publish Form "
Then the form should be made accessible to students
And students should be able to submit their data .

**Comment by urt23** [comment]
https://github.com/user-attachments/assets/2556c876-88b2-45a6-b3ce-8e59d3537a49
