### ISSUE TITLE
[TF29] Feature : Display Student Details Form

### ISSUE THREAD

**Issue by muresaijaideepreddy** [phanijyothi11-tamu/team-formation#66]
Feature : Display Student Details Form
As a student , I want to view the form for entering my details .
Scenario : Student views the details form after logging in
Given I am logged in as a student
When I navigate to the " Student Details " page
Then I should see a form to enter my student details
And I should see fields for my name , email , and enrolled courses and other preferences
And I should see a submit button to save my detailsFeature : Edit Student Details Form
As a student , I want to edit my details in the form .
Scenario : Student edits their details after logging in
Given I am logged in as a student
And I have already filled out my student details
When I navigate to the " Edit Student Details " page
Then I should see a form pre - filled with my current details
And I should see fields for my name , email , enrolled courses , and other preferences
And I should see a submit button to save my updated details
Scenario : Student submits updated details
Given I am logged in as a student
And I have already filled out my student details
When I navigate to the " Edit Student Details " page
And I update my name to "New Name "
And I update my email to " newemail@example .com "
And I click the submit button
Then I should see a confirmation message saying " Your details have been updated successfully
"
And my updated details should be displayed on the " Student Details " page

**Comment by rithikasapparapu** [comment]
Feature: Student Form Submission
  As a student,
  So that I can provide my details for team formation,
  I want to fill out and submit the form created by the professor.

  Scenario: Student fills and submits the form successfully
    Given I am logged in as a student,
    And I have access to the published form,
    When I view the form,
    Then I should see the form with fields corresponding to the questions and attributes created by the professor.
    When I enter my details into the form fields,
    And I submit the form by clicking the "Submit" button,
    Then I should see a confirmation message "Response submitted successfully."
