### ISSUE TITLE
[TF30] Populate teams by gender - part 1

### ISSUE THREAD

**Issue by muresaijaideepreddy** [phanijyothi11-tamu/team-formation#67]
Feature : Team Formation
As a professor ,
So that I can ensure gender representation ( female and other non - male genders ) in teams ,
I want the system to include at least two individuals from these gender groups
Scenario : System ensures at least two individuals from gender groups ( female and other non -
male genders ) in teams
Given the submission period has closed
When the system processes student data for team formation
Then each team should include at least two individuals from gender groups ( female and other
non - male genders ) if applicable

**Comment by ramya-gotika** [comment]
This ticket represents the implementation of back-end logic to process student data and ensure gender representation in team formation.
Testing for this feature is pending and will be completed in a subsequent sprint.
