### ISSUE TITLE
[TF32] Set Attribute Weightage with Total Sum Constraint

### ISSUE THREAD

**Issue by muresaijaideepreddy** [phanijyothi11-tamu/team-formation#69]
Feature : Set Attribute Weightage with Total Sum ConstraintAs a professor ,
So that the team formation algorithm can prioritize factors appropriately ,
I want to set weightages for attributes while ensuring their sum equals 1. Background : Given
I am logged in as a professor And I am on the form editing page
Scenario : Professor attempts to update weightage of an existing attribute exceeding total
weightage of 1
Given I have attributes with total weightage 1.0
When I update the weightage of " Programming Proficiency " from 0.5 to 0.6 Then the weightage
for " Programming Proficiency " should be updated to 0.6
And I should see a notification " Total weightage is 1.1. Weightages should sum to 1."

**Comment by Sahithi1214** [comment]
Ticket Update 1: 
Weightage Feature Demo Video : https://github.com/user-attachments/assets/65e59c7b-2eb1-4bcc-9d65-0a6d440f23d8

Implementations in this ticket : 
Introduced Total Weightage Constraint - to be 1
Changed update_weightage function - to prevent complexity issue in code report generation - code climate
Removed flash message duplication error in the instructor form page

Pending : 
Cucumber and Rspec tests

**Comment by Sahithi1214** [comment]
Coverage after adding rspec and cucumber : 
![Image](https://github.com/user-attachments/assets/d5427678-c383-44da-a0c8-3d862359a08c)

![Image](https://github.com/user-attachments/assets/df321f0b-977f-422b-971a-47451227b942)
