### ISSUE TITLE
[TF33] Ethnicity Code Implementation - Part 1

### ISSUE THREAD

**Issue by muresaijaideepreddy** [phanijyothi11-tamu/team-formation#70]
Feature : Team FormationAs a professor ,
So that I can ensure inclusivity in teams ,
I want the system to include at least two individuals from underrepresented groups .
Scenario : System includes underrepresented groups in teams
Given the submission period has closed
When the system processes student data for team formation
Then each team should include at least two individuals from underrepresented ethnic groups
if applicable

**Comment by Sahithi1214** [comment]
Initial backend logic code is available on branch TF33 - app/controllers/forms_controller/ - Lines 286-470
This includes 
1) Swaps between the genders that have already been assigned to see if I can improve the implementation of ethnic diversity
2) Calculation of the weighted average score of each team to minimize the number of swaps needed once the ethnicities are set
3) Assigning teams based on minority ethnicities
4) Integrating other minority groups with the existing minority teams

Implementation left : 
1) A function to calculate students who have not been assigned so far once teams are formed based on gender
2) Changes in analyze_teams function to bring ethnicity attribute from form responses
3) Logic addition to compare existing team weightage before adding student to team
4) Finalizing the team compositions
5) Rspec and Cucumber test cases
