### ISSUE TITLE
[TF34] Programming Proficiency Code Implementation - Part 1

### ISSUE THREAD

**Issue by muresaijaideepreddy** [phanijyothi11-tamu/team-formation#71]
Feature : Team Formation
As a professor ,
So that I can ensure diverse programming skills within teams ,
I want the system to include students with varied programming proficiency in each team .
Scenario : System ensures varied programming proficiency in teams
Given the submission period has closed
When the system processes student data for team formation
Then each team should include students with different levels of programming proficiency

**Comment by rithikasapparapu** [comment]
This code implementation analyzes student teams based on form responses, and distributes remaining unallocated students to the teams based on programming efficiency scores.
Testing the functionality by writing tests and covering edge cases will be addressed in the next sprint as part of part 2 of this ticket.
