### ISSUE TITLE
[TF 35] Invalid forms student side

### ISSUE THREAD

**Issue by muresaijaideepreddy** [phanijyothi11-tamu/team-formation#72]
Scenario : Student leaves required fields empty
Given I am filling out the form ,
When I leave any required field empty ,
And I attempt to submit the form ,
Then I should see an error message indicating that all required fields must be filled ,
And the form should not be submitted until all required fields are completed .
Scenario : Student enters invalid data into a field
Given I am filling out the form ,
When I enter invalid data into one or more fields (e.g., entering non - numeric data in a
numeric field ),
And I attempt to submit the form ,
Then I should see an error message indicating which fields contain invalid data ,
And the form should not be submitted until the invalid data is corrected .

**Comment by phanijyothi11-tamu** [comment]
Feature : Edit Student Details Form
As a student , I want to edit my details in the form .
Scenario : Student edits their details after logging in
Given I am logged in as a student
And I have already filled out my student details
When I navigate to the " Edit Student Details " page
Then I should see a form pre - filled with my current details
And I should see fields for my name , email , enrolled courses , and other preferences
And I should see a submit button to save my updated details
Scenario : Student submits updated details
Given I am logged in as a student
And I have already filled out my student details
When I navigate to the " Edit Student Details " page
And I update my name to "New Name "
And I update my email to " newemail@example .com "
And I click the submit button
Then I should see a confirmation message saying " Your details have been updated successfully
"
And my updated details should be displayed on the " Student Details " page
